### ISSUE TITLE
搜索时加粗的文字不准

### ISSUE THREAD

**Issue by iamqiz** [acgq/Switcheroo#1]
谢谢大佬改进让Switcheroo支持拼音❤
我发现一个小问题
搜索时加粗的文字不准
搜: 递归搜索子
![PixPin_2024-10-20_18-22-18](https://github.com/user-attachments/assets/8ccebc4c-4146-4be7-b29f-91ee7d622b45)

搜 更加安全和得心应手
![PixPin_2024-10-20_18-27-18](https://github.com/user-attachments/assets/6decc9b2-183c-4b5d-bb4c-c96ab42afef1)

**Comment by acgq** [comment]
是有点问题，改过了
我把Release里的文件替换了，重新下载安装下就行
